/**
 * Copyright 2024 See AUTHORS file.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package asg.games.yipee.net.packets;

import asg.games.yipee.common.enums.YipeeSerializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Base type for all client-to-server request packets.
 *
 * <p>This abstract class defines the common envelope fields that every
 * client request must carry when communicating with the Yipee game server:
 *
 * <ul>
 *   <li>{@code clientId} – identifies the client device/instance.</li>
 *   <li>{@code authToken} – proves who the user is (issued by WordPress/IdP).</li>
 *   <li>{@code sessionId} – identifies the active game session.</li>
 *   <li>{@code clientTick} – the client's notion of the game tick at send time.</li>
 *   <li>{@code timestamp} – local send time in milliseconds (diagnostics only).</li>
 * </ul>
 *
 * <p>Concrete request types (e.g., seat selection, input actions, table updates)
 * should extend this class and add their own payload fields as needed. KryoNet
 * will serialize subclasses according to the packet registration performed at
 * startup.
 *
 * <p>Equality and hash code are generated by Lombok and explicitly exclude
 * {@code timestamp}, so that logically identical requests with different send
 * times compare equal.
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false, exclude = {"timestamp"})
public abstract class AbstractClientRequest implements YipeeSerializable {
    /**
     * Identifier of the game/table context associated with this response.
     *
     * <p>If the response does not pertain to a specific game (e.g., handshake),
     * this field may be null.
     */
    private String gameId;

    /**
     * A stable identifier for the client instance (device, browser, or app install).
     * <p>
     * This value is typically generated by the client and persisted locally, and is
     * used by the server for logging, analytics, and optional multi-device policies.
     * It is not treated as a secret or security credential.
     */
    private String clientId;

    /**
     * Authentication token proving the identity of the user sending this request.
     *
     * <p>In production, this is expected to be a JWT (or similar token) issued by
     * the web CMS or identity provider (e.g., WordPress). The server validates the
     * token and uses its claims to resolve the associated player identity.
     *
     * <p>Depending on deployment mode, this field may be:
     * <ul>
     *   <li>Required, when an external IdP is configured.</li>
     *   <li>Optional, when the Yipee server operates in a standalone/self-auth mode.</li>
     * </ul>
     */
    private String authToken;

    /**
     * Identifier of the active game session to which this request belongs.
     *
     * <p>The session ID is always generated and owned by the server after a successful
     * handshake. Clients must include it in subsequent requests so the server can
     * route actions and state changes to the correct game/table context.
     */
    private String sessionId;

    /**
     * The client's notion of the game tick when this request was created.
     *
     * <p>Used by the authoritative server loop to correlate actions with the
     * client's predicted state and to support features like reconciliation,
     * rollback, or latency-compensated input handling.
     */
    private long clientTick;

    /**
     * Local system time in milliseconds (typically {@code System.currentTimeMillis()})
     * at the moment the request was sent.
     *
     * <p>This value is intended for latency diagnostics, metrics, and logging only.
     * It must not be used as a source of game logic truth, since it is controlled
     * by the client and may be skewed or manipulated.
     */
    private long timestamp;

    @Override
    public String toString() {
        return "ClientRequest[" + clientId + ", clientTick=" + clientTick + ", ts=" + timestamp + "]";
    }
}
